xpert-framework-master/src/main/java/com/xpert/maker/model/ViewEntity.java
package com.xpert.maker.model;

import com.xpert.faces.primefaces.PrimeFacesUtils;
import com.xpert.faces.primefaces.PrimeFacesVersion;
import com.xpert.utils.StringUtils;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author ayslan
 */
public class ViewEntity {

    private String name;
    private String idFieldName;
    private boolean embeddedId;
    private boolean idAutoGenerated;
    private PrimeFacesVersion primeFacesVersion;
    private List<ViewField> fields = new ArrayList<ViewField>();

    public ViewEntity() {
        primeFacesVersion = PrimeFacesVersion.VERSION_3;
    }

    
    
    public String getAppendTo(){
        if(primeFacesVersion.isUseAppendTo()){
            return "appendTo=\"@(body)\"";
        }else{
            return "appendToBody=\"true\"";
        }
    }
    
    public String getWidgetVarDetailName() {
        return "widget" + name + "Detail";
    }
    
    public String getWidgetVarDataTableName() {
        return "dataTable" + name + "Widget";
    }
    
    public String getWidgetVarDetail() {
        String widgetVar = getWidgetVarDetailName();
        if (primeFacesVersion != null) {
            widgetVar = PrimeFacesUtils.normalizeWidgetVar(widgetVar, primeFacesVersion);
        }
        return widgetVar;
    }

    public String getWidgetVarDataTable() {
        String widgetVar = getWidgetVarDataTableName();
        if (primeFacesVersion != null) {
            widgetVar = PrimeFacesUtils.normalizeWidgetVar(widgetVar, primeFacesVersion);
        }
        return widgetVar;
    }

    public String getNameLower() {
        if (name != null) {
            return StringUtils.getLowerFirstLetter(name);
        }
        return name;
    }

    public boolean isEmbeddedId() {
        return embeddedId;
    }

    public void setEmbeddedId(boolean embeddedId) {
        this.embeddedId = embeddedId;
    }
    
    public String getIdFieldName() {
        return idFieldName;
    }

    public void setIdFieldName(String idFieldName) {
        this.idFieldName = idFieldName;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<ViewField> getFields() {
        return fields;
    }

    public void setFields(List<ViewField> fields) {
        this.fields = fields;
    }

    public PrimeFacesVersion getPrimeFacesVersion() {
        return primeFacesVersion;
    }

    public void setPrimeFacesVersion(PrimeFacesVersion primeFacesVersion) {
        this.primeFacesVersion = primeFacesVersion;
    }

    public boolean isIdAutoGenerated() {
        return idAutoGenerated;
    }

    public void setIdAutoGenerated(boolean idAutoGenerated) {
        this.idAutoGenerated = idAutoGenerated;
    }

    
}

xpert-framework-master/src/main/java/com/xpert/maker/model/ViewField.java
package com.xpert.maker.model;

import com.xpert.utils.StringUtils;

/**
 *
 * @author ayslan
 */
public class ViewField {

    private String name;
    private String label;
    private String typeName;
    private boolean required;
    private boolean id;
    private boolean embeddedId;
    private boolean oneToOne;
    private boolean oneToMany;
    private boolean manyToOne;
    private boolean manyToMany;
    private boolean lazy;
    private boolean decimal;
    private boolean integer;
    private boolean date;
    private boolean time;
    private boolean yesNo;
    private boolean enumeration;
    private boolean string;
    private String maxlength;
    private ViewEntity viewEntity;
    
    public boolean isRenderFieldInFormCreate(){
        return (id == false && (embeddedId || yesNo || string || integer || decimal || date 
                || time || enumeration || manyToMany || manyToOne ))
                || (id == true && viewEntity != null && !viewEntity.isIdAutoGenerated());
    }

    public String getTypeNameLower() {
        if (typeName != null) {
            return StringUtils.getLowerFirstLetter(typeName);
        }
        return typeName;
    }

    public String getLabel() {
        return label;
    }

    public void setLabel(String label) {
        this.label = label;
    }
    
    public boolean isEmbeddedId() {
        return embeddedId;
    }

    public void setEmbeddedId(boolean embeddedId) {
        this.embeddedId = embeddedId;
    }
    
    public boolean isTime() {
        return time;
    }

    public void setTime(boolean time) {
        this.time = time;
    }
    
    public boolean isString() {
        return string;
    }

    public void setString(boolean string) {
        this.string = string;
    }

    public boolean isRequired() {
        return required;
    }

    public void setRequired(boolean required) {
        this.required = required;
    }

    public boolean isEnumeration() {
        return enumeration;
    }

    public void setEnumeration(boolean enumeration) {
        this.enumeration = enumeration;
    }

    public String getTypeName() {
        return typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public boolean isManyToMany() {
        return manyToMany;
    }

    public void setManyToMany(boolean manyToMany) {
        this.manyToMany = manyToMany;
    }

    public boolean isManyToOne() {
        return manyToOne;
    }

    public void setManyToOne(boolean manyToOne) {
        this.manyToOne = manyToOne;
    }

    public boolean isOneToMany() {
        return oneToMany;
    }

    public void setOneToMany(boolean oneToMany) {
        this.oneToMany = oneToMany;
    }

    public boolean isOneToOne() {
        return oneToOne;
    }

    public void setOneToOne(boolean oneToOne) {
        this.oneToOne = oneToOne;
    }

    public boolean isCollection() {
        return oneToMany || manyToMany;
    }

    public boolean isId() {
        return id;
    }

    public void setId(boolean id) {
        this.id = id;
    }

    public boolean isDate() {
        return date;
    }

    public void setDate(boolean date) {
        this.date = date;
    }

    public boolean isDecimal() {
        return decimal;
    }

    public void setDecimal(boolean decimal) {
        this.decimal = decimal;
    }

    public boolean isInteger() {
        return integer;
    }

    public void setInteger(boolean integer) {
        this.integer = integer;
    }

    public boolean isLazy() {
        return lazy;
    }

    public void setLazy(boolean lazy) {
        this.lazy = lazy;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public boolean isYesNo() {
        return yesNo;
    }

    public void setYesNo(boolean yesNo) {
        this.yesNo = yesNo;
    }

    public String getMaxlength() {
        return maxlength;
    }

    public void setMaxlength(String maxlength) {
        this.maxlength = maxlength;
    }

    public ViewEntity getViewEntity() {
        return viewEntity;
    }

    public void setViewEntity(ViewEntity viewEntity) {
        this.viewEntity = viewEntity;
    }

    
  
}

xpert-framework-master/src/main/java/com/xpert/maker/Bean.java
package com.xpert.maker;

import com.xpert.maker.model.ViewEntity;

/**
 *
 * @author ayslan
 */
public class Bean {

    private Class entity;
    private BeanType beanType;
    private BeanConfiguration configuration;
    private String author;
    private String resourceBundle;
    private ViewEntity viewEntity;
    
    public Bean(Class entity, BeanType beanType) {
        this.entity = entity;
        this.beanType = beanType;
    }
    
    public String getNameLower() {
        String name = getName();
        if (name != null && name.length() > 2) {
            return name.substring(0, 2).toLowerCase() + "" + name.substring(2, name.length());
        }
        return "";
    }

    public ViewEntity getViewEntity() {
        return viewEntity;
    }

    public void setViewEntity(ViewEntity viewEntity) {
        this.viewEntity = viewEntity;
    }
    
    public String getResourceBundle() {
        return resourceBundle;
    }

    public void setResourceBundle(String resourceBundle) {
        this.resourceBundle = resourceBundle;
    }
    
    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public BeanConfiguration getConfiguration() {
        return configuration;
    }

    public void setConfiguration(BeanConfiguration configuration) {
        this.configuration = configuration;
    }

    public BeanType getBeanType() {
        return beanType;
    }

    public void setBeanType(BeanType beanType) {
        this.beanType = beanType;
    }
    
    public Class getEntity() {
        return entity;
    }

    public void setEntity(Class entity) {
        this.entity = entity;
    }

    public String getName() {
        if (entity != null) {
            return entity.getSimpleName();
        }
        return null;
    }
}

xpert-framework-master/src/main/resources/com/xpert/maker/templates/bootstrap/view-detail.ftl
<ui:composition  xmlns="http://www.w3.org/1999/xhtml"
                 xmlns:h="http://java.sun.com/jsf/html"
                 xmlns:f="http://java.sun.com/jsf/core"
                 xmlns:ui="http://java.sun.com/jsf/facelets"
                 xmlns:p="http://primefaces.org/ui"
                 xmlns:x="http://xpert.com/faces">
    <h:form id="formDetail${entity.name}" styleClass="uix-form-detail">
        <div class="container-fluid">
            <div class="row">
            <#list entity.fields as field>
                <#if field.collection == false && field.id == false>
                <div class="${configuration.bootstrapVersion.defaultColumns}">
                    <h:outputLabel value="${sharp}{${resourceBundle}['${entity.nameLower}.${field.label}']}:" styleClass="control-label" /><br/>
                    <#if field.lazy == true>
                    <h:outputText value="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.entity.${field.name}}" styleClass="uix-content-detail">
                        <x:initializer/>
                    </h:outputText>
                    </#if>
                    <#if field.decimal == true>
                    <h:outputText value="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.entity.${field.name}}" styleClass="uix-content-detail">
                        <f:convertNumber minFractionDigits="2" maxFractionDigits="2" />
                    </h:outputText>
                    </#if>
                    <#if field.date == true>
                    <h:outputText value="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.entity.${field.name}}" styleClass="uix-content-detail">
                        <f:convertDateTime />
                    </h:outputText>
                    </#if>
                    <#if field.time == true>
                    <h:outputText value="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.entity.${field.name}}" styleClass="uix-content-detail">
                        <f:convertDateTime pattern="${configuration.timePattern}"/>
                    </h:outputText>
                    </#if>
                    <#if field.yesNo == true>
                    <h:outputText value="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.entity.${field.name}}" converter ="yesNoConverter"  styleClass="uix-content-detail"/>
                    </#if>
                    <#if field.lazy == false && field.decimal == false && field.date == false && field.time == false && field.yesNo == false>
                    <h:outputText value="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.entity.${field.name}}" styleClass="uix-content-detail"/>
                    </#if>
                </div>
                </#if>
            </#list>
           </div>
         </div>
        <p:separator/>
        <div class="uix-center">
            <p:commandButton type="button" value="${sharp}{xmsg['close']}" onclick="${entity.widgetVarDetail}.hide()" />
            <#if configuration.generatesSecurityArea == true >
            <x:securityArea rolesAllowed="${entity.nameLower}.audit">
                <x:audit for="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.entity}"/>
            </x:securityArea>
            <#else>
            <x:audit for="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.entity}"/>
            </#if>
        </div>
    </h:form>
</ui:composition>

xpert-framework-master/src/main/resources/com/xpert/maker/templates/bootstrap/view-form-create.ftl
<ui:composition  xmlns="http://www.w3.org/1999/xhtml"
                 xmlns:h="http://java.sun.com/jsf/html"
                 xmlns:f="http://java.sun.com/jsf/core"
                 xmlns:ui="http://java.sun.com/jsf/facelets"
                 xmlns:p="http://primefaces.org/ui"
                 xmlns:x="http://xpert.com/faces">
    
  
    <h:form id="formCreate${entity.name}" >
        <p:fieldset legend="${sharp}{xmsg['generalData']}">
            <x:modalMessages/>

            <div class="container-fluid">
                 <div class="row">
                 <#list entity.fields as field>
                 <#if field.renderFieldInFormCreate == true >
                      <div class="form-group ${configuration.bootstrapVersion.defaultColumns}">
                         <#-- Boolean -->
                         <#if field.yesNo == true>
                         <div class="checkbox">
                             <label>
                                 <h:selectBooleanCheckbox id="${field.label}" value="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.entity.${field.name}}" />
                                 ${sharp}{${resourceBundle}['${entity.nameLower}.${field.label}']}
                             </label>
                         </div>
                         </#if>
                         <#-- Others -->
                         <#if field.yesNo == false>
                         <#-- String -->
                         <#if field.string == true>
                         <h:outputLabel for="${field.label}" value="<#if field.required == true>* </#if>${sharp}{${resourceBundle}['${entity.nameLower}.${field.label}']}:" />
                         <p:inputText id="${field.label}" value="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.entity.${field.name}}" maxlength="${field.maxlength?string}"  styleClass="form-control"  />
                         </#if>
                         <#-- Integer/Long -->
                         <#if field.integer == true>
                         <h:outputLabel for="${field.label}" value="<#if field.required == true>* </#if>${sharp}{${resourceBundle}['${entity.nameLower}.${field.label}']}:" />
                         <p:inputMask id="${field.label}" mask="9?999999999" placeHolder="" value="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.entity.${field.name}}" styleClass="form-control" />
                         </#if>
                         <#-- Decimal (BigDecimal, Double) -->
                         <#if field.decimal == true>
                         <h:outputLabel for="${field.label}" value="<#if field.required == true>* </#if>${sharp}{${resourceBundle}['${entity.nameLower}.${field.label}']}:" />
                         <x:inputNumber id="${field.label}" value="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.entity.${field.name}}" styleClass="form-control"/>
                         </#if>
                         <#-- Date p:calendar wont work with form-control, he has a span over the input and class goes for span -->
                         <#if field.date == true>
                         <h:outputLabel for="${field.label}" value="<#if field.required == true>* </#if>${sharp}{${resourceBundle}['${entity.nameLower}.${field.label}']}:" />
                         <#if configuration.maskCalendar == true>
                         <p:calendar id="${field.label}" value="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.entity.${field.name}}" 
                                     showOn="button" pattern="${configuration.datePattern}" styleClass="uix-calendar"  >
                             <x:mask/>
                         </p:calendar>
                         <#else>
                         <p:calendar id="${field.label}" value="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.entity.${field.name}}" 
                                     showOn="button" pattern="${configuration.datePattern}" styleClass="uix-calendar" />
                         </#if>
                         </#if>
                          <#-- Time -->
                         <#if field.time == true>
                         <h:outputLabel for="${field.label}" value="<#if field.required == true>* </#if>${sharp}{${resourceBundle}['${entity.nameLower}.${field.label}']}:" />
                         <#if configuration.maskCalendar == true>
                         <p:calendar id="${field.label}" value="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.entity.${field.name}}" 
                                     showOn="button" pattern="${configuration.timePattern}" timeOnly="true" styleClass="uix-calendar">
                             <x:mask/>
                         </p:calendar>
                         <#else>
                         <p:calendar id="${field.label}" value="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.entity.${field.name}}" 
                                     showOn="button" pattern="${configuration.timePattern}" timeOnly="true" styleClass="uix-calendar"/>
                         </#if>
                         </#if>
                         <#-- Enuns/ManyToOne (render a combobox) -->
                         <#if field.enumeration == true || field.manyToOne == true>
                         <h:outputLabel for="${field.label}" value="<#if field.required == true>* </#if>${sharp}{${resourceBundle}['${entity.nameLower}.${field.label}']}:" />
                         <h:selectOneMenu id="${field.label}" value="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.entity.${field.name}}" <#if field.enumeration == false>converter="entityConverter"</#if> styleClass="form-control" >
                             <#if field.lazy == true>
                             <x:initializer/>
                             </#if>
                             <f:selectItem itemLabel="${sharp}{xmsg['select']}" />
                             <f:selectItems value="${sharp}{findAllBean.get(class${configuration.managedBeanSuffix}.${field.typeNameLower})}" 
                                            var="${field.typeNameLower}"
                                            itemLabel="${sharp}{${field.typeNameLower}}"/>
                         </h:selectOneMenu>
                         </#if>
                         <#-- Collections (render a checkbox list) -->
                         <#if field.manyToMany == true >
                         <h:outputLabel value="<#if field.required == true>* </#if>${sharp}{${resourceBundle}['${entity.nameLower}.${field.label}']}:" />
                         <h:selectManyCheckbox id="${field.label}" value="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.entity.${field.name}}" converter="entityConverter" >
                             <#if field.lazy == true>
                             <x:initializer/>
                             </#if>
                             <f:selectItems value="${sharp}{findAllBean.get(class${configuration.managedBeanSuffix}.${field.typeNameLower})}" 
                                            var="${field.typeNameLower}"
                                            itemLabel="${sharp}{${field.typeNameLower}}"/>
                         </h:selectManyCheckbox>
                         </#if>
                         </#if>
                     </div>
                 </#if>
                 </#list>

                 </div>
             </div>
        </p:fieldset>
        <h:outputText value="${sharp}{xmsg['requiredFieldsForm']}"/>
        <div class="uix-center">
            <#if configuration.generatesSecurityArea == true >
            <x:securityArea rolesAllowed="${entity.nameLower}.create">
                <p:commandButton process="@form" update="@form" action="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.save}" value="${sharp}{xmsg['save']}" />
            </x:securityArea>
            <x:securityArea rolesAllowed="${entity.nameLower}.audit">
                <x:audit for="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.entity}"/>
            </x:securityArea>
            <#else>
            <p:commandButton process="@form" update="@form" action="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.save}" value="${sharp}{xmsg['save']}" />
            <x:audit for="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.entity}"/>
            </#if>
        </div>
    </h:form>

</ui:composition>