xpert-framework-master/src/main/java/com/xpert/maker/model/ViewEntity.java
package com.xpert.maker.model;

import com.xpert.faces.primefaces.PrimeFacesUtils;
import com.xpert.faces.primefaces.PrimeFacesVersion;
import com.xpert.utils.StringUtils;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author ayslan
 */
public class ViewEntity {

    private String name;
    private String idFieldName;
    private boolean embeddedId;
    private boolean idAutoGenerated;
    private PrimeFacesVersion primeFacesVersion;
    private List<ViewField> fields = new ArrayList<ViewField>();

    public ViewEntity() {
        primeFacesVersion = PrimeFacesVersion.VERSION_3;
    }

    
    
    public String getAppendTo(){
        if(primeFacesVersion.isUseAppendTo()){
            return "appendTo=\"@(body)\"";
        }else{
            return "appendToBody=\"true\"";
        }
    }
    
    public String getWidgetVarDetailName() {
        return "widget" + name + "Detail";
    }
    
    public String getWidgetVarDataTableName() {
        return "dataTable" + name + "Widget";
    }
    
    public String getWidgetVarDetail() {
        String widgetVar = getWidgetVarDetailName();
        if (primeFacesVersion != null) {
            widgetVar = PrimeFacesUtils.normalizeWidgetVar(widgetVar, primeFacesVersion);
        }
        return widgetVar;
    }

    public String getWidgetVarDataTable() {
        String widgetVar = getWidgetVarDataTableName();
        if (primeFacesVersion != null) {
            widgetVar = PrimeFacesUtils.normalizeWidgetVar(widgetVar, primeFacesVersion);
        }
        return widgetVar;
    }

    public String getNameLower() {
        if (name != null) {
            return StringUtils.getLowerFirstLetter(name);
        }
        return name;
    }

    public boolean isEmbeddedId() {
        return embeddedId;
    }

    public void setEmbeddedId(boolean embeddedId) {
        this.embeddedId = embeddedId;
    }
    
    public String getIdFieldName() {
        return idFieldName;
    }

    public void setIdFieldName(String idFieldName) {
        this.idFieldName = idFieldName;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<ViewField> getFields() {
        return fields;
    }

    public void setFields(List<ViewField> fields) {
        this.fields = fields;
    }

    public PrimeFacesVersion getPrimeFacesVersion() {
        return primeFacesVersion;
    }

    public void setPrimeFacesVersion(PrimeFacesVersion primeFacesVersion) {
        this.primeFacesVersion = primeFacesVersion;
    }

    public boolean isIdAutoGenerated() {
        return idAutoGenerated;
    }

    public void setIdAutoGenerated(boolean idAutoGenerated) {
        this.idAutoGenerated = idAutoGenerated;
    }

    
}

xpert-framework-master/src/main/java/com/xpert/maker/model/ViewField.java
package com.xpert.maker.model;

import com.xpert.utils.StringUtils;

/**
 *
 * @author ayslan
 */
public class ViewField {

    private String name;
    private String label;
    private String typeName;
    private boolean required;
    private boolean id;
    private boolean embeddedId;
    private boolean oneToOne;
    private boolean oneToMany;
    private boolean manyToOne;
    private boolean manyToMany;
    private boolean lazy;
    private boolean decimal;
    private boolean integer;
    private boolean date;
    private boolean time;
    private boolean yesNo;
    private boolean enumeration;
    private boolean string;
    private String maxlength;
    private ViewEntity viewEntity;
    
    public boolean isRenderFieldInFormCreate(){
        return (id == false && (embeddedId || yesNo || string || integer || decimal || date 
                || time || enumeration || manyToMany || manyToOne ))
                || (id == true && viewEntity != null && !viewEntity.isIdAutoGenerated());
    }

    public String getTypeNameLower() {
        if (typeName != null) {
            return StringUtils.getLowerFirstLetter(typeName);
        }
        return typeName;
    }

    public String getLabel() {
        return label;
    }

    public void setLabel(String label) {
        this.label = label;
    }
    
    public boolean isEmbeddedId() {
        return embeddedId;
    }

    public void setEmbeddedId(boolean embeddedId) {
        this.embeddedId = embeddedId;
    }
    
    public boolean isTime() {
        return time;
    }

    public void setTime(boolean time) {
        this.time = time;
    }
    
    public boolean isString() {
        return string;
    }

    public void setString(boolean string) {
        this.string = string;
    }

    public boolean isRequired() {
        return required;
    }

    public void setRequired(boolean required) {
        this.required = required;
    }

    public boolean isEnumeration() {
        return enumeration;
    }

    public void setEnumeration(boolean enumeration) {
        this.enumeration = enumeration;
    }

    public String getTypeName() {
        return typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public boolean isManyToMany() {
        return manyToMany;
    }

    public void setManyToMany(boolean manyToMany) {
        this.manyToMany = manyToMany;
    }

    public boolean isManyToOne() {
        return manyToOne;
    }

    public void setManyToOne(boolean manyToOne) {
        this.manyToOne = manyToOne;
    }

    public boolean isOneToMany() {
        return oneToMany;
    }

    public void setOneToMany(boolean oneToMany) {
        this.oneToMany = oneToMany;
    }

    public boolean isOneToOne() {
        return oneToOne;
    }

    public void setOneToOne(boolean oneToOne) {
        this.oneToOne = oneToOne;
    }

    public boolean isCollection() {
        return oneToMany || manyToMany;
    }

    public boolean isId() {
        return id;
    }

    public void setId(boolean id) {
        this.id = id;
    }

    public boolean isDate() {
        return date;
    }

    public void setDate(boolean date) {
        this.date = date;
    }

    public boolean isDecimal() {
        return decimal;
    }

    public void setDecimal(boolean decimal) {
        this.decimal = decimal;
    }

    public boolean isInteger() {
        return integer;
    }

    public void setInteger(boolean integer) {
        this.integer = integer;
    }

    public boolean isLazy() {
        return lazy;
    }

    public void setLazy(boolean lazy) {
        this.lazy = lazy;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public boolean isYesNo() {
        return yesNo;
    }

    public void setYesNo(boolean yesNo) {
        this.yesNo = yesNo;
    }

    public String getMaxlength() {
        return maxlength;
    }

    public void setMaxlength(String maxlength) {
        this.maxlength = maxlength;
    }

    public ViewEntity getViewEntity() {
        return viewEntity;
    }

    public void setViewEntity(ViewEntity viewEntity) {
        this.viewEntity = viewEntity;
    }

    
  
}

xpert-framework-master/src/main/java/com/xpert/maker/Bean.java
package com.xpert.maker;

import com.xpert.maker.model.ViewEntity;

/**
 *
 * @author ayslan
 */
public class Bean {

    private Class entity;
    private BeanType beanType;
    private BeanConfiguration configuration;
    private String author;
    private String resourceBundle;
    private ViewEntity viewEntity;
    
    public Bean(Class entity, BeanType beanType) {
        this.entity = entity;
        this.beanType = beanType;
    }
    
    public String getNameLower() {
        String name = getName();
        if (name != null && name.length() > 2) {
            return name.substring(0, 2).toLowerCase() + "" + name.substring(2, name.length());
        }
        return "";
    }

    public ViewEntity getViewEntity() {
        return viewEntity;
    }

    public void setViewEntity(ViewEntity viewEntity) {
        this.viewEntity = viewEntity;
    }
    
    public String getResourceBundle() {
        return resourceBundle;
    }

    public void setResourceBundle(String resourceBundle) {
        this.resourceBundle = resourceBundle;
    }
    
    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public BeanConfiguration getConfiguration() {
        return configuration;
    }

    public void setConfiguration(BeanConfiguration configuration) {
        this.configuration = configuration;
    }

    public BeanType getBeanType() {
        return beanType;
    }

    public void setBeanType(BeanType beanType) {
        this.beanType = beanType;
    }
    
    public Class getEntity() {
        return entity;
    }

    public void setEntity(Class entity) {
        this.entity = entity;
    }

    public String getName() {
        if (entity != null) {
            return entity.getSimpleName();
        }
        return null;
    }
}

xpert-framework-master/src/main/java/com/xpert/maker/MappedBean.java
package com.xpert.maker;

import com.xpert.utils.HumaniseCamelCase;

/**
 *
 * @author ayslan
 */
public class MappedBean {

    private Class entityClass;
    private String className;
    private String i18n;
    private String managedBean;
    private String businnesObject;
    private String dao;
    private String daoImpl;
    //XHTML
    private String createView;
    private String formCreateView;
    private String listView;
    private String menu;
    private String detail;

    public MappedBean() {
    }

    public String getHumanClassName() {
        if (entityClass != null) {
            return new HumaniseCamelCase().humanise(entityClass.getSimpleName());
        }
        return null;
    }

    public String getClassName() {
        if (entityClass != null) {
            return entityClass.getName();
        }
        return className;
    }

    public MappedBean(Class entityClass) {
        this.entityClass = entityClass;
    }

    public String getDetail() {
        return detail;
    }

    public void setDetail(String detail) {
        this.detail = detail;
    }

    public String getMenu() {
        return menu;
    }

    public void setMenu(String menu) {
        this.menu = menu;
    }

    public String getCreateView() {
        return createView;
    }

    public void setCreateView(String createView) {
        this.createView = createView;
    }

    public String getFormCreateView() {
        return formCreateView;
    }

    public void setFormCreateView(String formCreateView) {
        this.formCreateView = formCreateView;
    }

    public String getListView() {
        return listView;
    }

    public void setListView(String listView) {
        this.listView = listView;
    }

    public String getDaoImpl() {
        return daoImpl;
    }

    public void setDaoImpl(String daoImpl) {
        this.daoImpl = daoImpl;
    }

    public String getBusinnesObject() {
        return businnesObject;
    }

    public void setBusinnesObject(String businnesObject) {
        this.businnesObject = businnesObject;
    }

    public String getDao() {
        return dao;
    }

    public void setDao(String dao) {
        this.dao = dao;
    }

    public String getManagedBean() {
        return managedBean;
    }

    public void setManagedBean(String managedBean) {
        this.managedBean = managedBean;
    }

    public Class getEntityClass() {
        return entityClass;
    }

    public void setEntityClass(Class entityClass) {
        this.entityClass = entityClass;
    }

    public String getI18n() {
        return i18n;
    }

    public void setI18n(String i18n) {
        this.i18n = i18n;
    }
}

xpert-framework-master/src/main/resources/com/xpert/maker/templates/business-object.ftl
package ${configuration.businessObject};

import com.xpert.core.crud.AbstractBusinessObject;
import ${configuration.dao}.${name}DAO;
import com.xpert.core.validation.UniqueField;
import com.xpert.core.exception.BusinessException;
import java.util.List;
import javax.ejb.EJB;
import javax.ejb.Stateless;
import ${entity.name};

/**
 *
 * @author ${author}
 */
@Stateless
public class ${name}${configuration.businessObjectSuffix} extends AbstractBusinessObject<${name}> {

    @EJB
    private ${name}DAO ${nameLower}DAO;
    
    @Override
    public ${name}DAO getDAO() {
        return ${nameLower}DAO;
    }

    @Override
    public List<UniqueField> getUniqueFields() {
        return null;
    }

    @Override
    public void validate(${name} ${nameLower}) throws BusinessException {
    }

    @Override
    public boolean isAudit() {
        return true;
    }

}

xpert-framework-master/src/main/resources/com/xpert/maker/templates/class-bean.ftl
package ${package};

<#list classes as clazz>
import ${clazz.name};
</#list>
import javax.faces.bean.ManagedBean;

@ManagedBean
public class Class${configuration.managedBeanSuffix} {

    <#list classes as class>
    public Class get${class.simpleName}() {
        return ${class.simpleName}.class;
    }
    </#list>

}

xpert-framework-master/src/main/resources/com/xpert/maker/templates/dao-impl.ftl
package ${configuration.daoImpl};

import ${configuration.baseDAO};
import ${configuration.dao}.${name}DAO;
import ${entity.name};
import javax.ejb.Stateless;

/**
 *
 * @author ${author}
 */
@Stateless
public class ${name}DAOImpl extends ${configuration.baseDAOSimpleName}<${name}> implements ${name}DAO {

    @Override
    public Class getEntityClass() {
        return ${name}.class;
    }

}

xpert-framework-master/src/main/resources/com/xpert/maker/templates/dao.ftl
package ${configuration.dao};

import com.xpert.persistence.dao.BaseDAO;
import ${entity.name};
import javax.ejb.Local;

/**
 *
 * @author ${author}
 */
@Local
public interface ${name}DAO extends BaseDAO<${name}> {
    
}

xpert-framework-master/src/main/resources/com/xpert/maker/templates/managed-bean.ftl
package ${configuration.managedBean};


import java.io.Serializable;
import com.xpert.core.crud.AbstractBaseBean;
import javax.ejb.EJB;
<#if configuration.useCDIBeans == false >
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
</#if>
<#if configuration.useCDIBeans == true >
import javax.faces.view.ViewScoped;
import javax.inject.Named; 
</#if>
import ${configuration.businessObject}.${name}${configuration.businessObjectSuffix};
import ${entity.name};

/**
 *
 * @author ${author}
 */
<#if configuration.useCDIBeans == false >
@ManagedBean
</#if>
<#if configuration.useCDIBeans == true >
@Named
</#if>
@ViewScoped
public class ${name}${configuration.managedBeanSuffix} extends AbstractBaseBean<${name}> implements Serializable {

    @EJB
    private ${name}${configuration.businessObjectSuffix} ${nameLower}${configuration.businessObjectSuffix};

    @Override
    public ${name}${configuration.businessObjectSuffix} getBO() {
        return ${nameLower}${configuration.businessObjectSuffix};
    }

    @Override
    public String getDataModelOrder() {
        return "${viewEntity.idFieldName}";
    }
    <#if configuration.hideIdInRequest == true >

    @Override
    public boolean isLoadEntityOnPostConstruct() {
        return false;
    }
    </#if>
}

xpert-framework-master/src/main/resources/com/xpert/maker/templates/view-create.ftl
<ui:composition  xmlns="http://www.w3.org/1999/xhtml"
                 xmlns:h="http://java.sun.com/jsf/html"
                 xmlns:f="http://java.sun.com/jsf/core"
                 xmlns:ui="http://java.sun.com/jsf/facelets"
                 xmlns:p="http://primefaces.org/ui"
                 template="${template}"
                 xmlns:x="http://xpert.com/faces">
   <ui:param name="title" value="${sharp}{${resourceBundle}['${entity.nameLower}.create']}" />
   <ui:define name="body">
       <ui:include src="menu${entity.name}.xhtml" />
       <ui:include src="formCreate${entity.name}.xhtml" />
   </ui:define>
</ui:composition>

xpert-framework-master/src/main/resources/com/xpert/maker/templates/view-detail.ftl
<ui:composition  xmlns="http://www.w3.org/1999/xhtml"
                 xmlns:h="http://java.sun.com/jsf/html"
                 xmlns:f="http://java.sun.com/jsf/core"
                 xmlns:ui="http://java.sun.com/jsf/facelets"
                 xmlns:p="http://primefaces.org/ui"
                 xmlns:x="http://xpert.com/faces">
    <h:form id="formDetail${entity.name}">
        <h:panelGrid columns="4" styleClass="grid-detail">
        <#list entity.fields as field>
            <#if field.collection == false && field.id == false>
           
            <h:outputLabel value="${sharp}{${resourceBundle}['${entity.nameLower}.${field.label}']}:" />
            <#if field.lazy == true>
            <h:outputText value="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.entity.${field.name}}">
                <x:initializer/>
            </h:outputText>
            </#if>
            <#if field.decimal == true>
            <h:outputText value="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.entity.${field.name}}">
                <f:convertNumber minFractionDigits="2" maxFractionDigits="2" />
            </h:outputText>
            </#if>
            <#if field.date == true>
            <h:outputText value="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.entity.${field.name}}">
                <f:convertDateTime />
            </h:outputText>
            </#if>
            <#if field.time == true>
            <h:outputText value="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.entity.${field.name}}">
                <f:convertDateTime pattern="${configuration.timePattern}"/>
            </h:outputText>
            </#if>
            <#if field.yesNo == true>
            <h:outputText value="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.entity.${field.name}}" converter ="yesNoConverter" />
            </#if>
            <#if field.lazy == false && field.decimal == false && field.date == false && field.time == false && field.yesNo == false>
            <h:outputText value="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.entity.${field.name}}"/>
            </#if>
            </#if>
        </#list>

        </h:panelGrid>
        <p:separator/>
        <div style="text-align: center;">
            <p:commandButton type="button" value="${sharp}{xmsg['close']}" onclick="${entity.widgetVarDetail}.hide()" />
            <#if configuration.generatesSecurityArea == true >
            <x:securityArea rolesAllowed="${entity.nameLower}.audit">
                <x:audit for="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.entity}"/>
            </x:securityArea>
            <#else>
            <x:audit for="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.entity}"/>
            </#if>
        </div>
    </h:form>
</ui:composition>

xpert-framework-master/src/main/resources/com/xpert/maker/templates/view-list.ftl
<ui:composition  xmlns="http://www.w3.org/1999/xhtml"
                 xmlns:h="http://java.sun.com/jsf/html"
                 xmlns:f="http://java.sun.com/jsf/core"
                 xmlns:ui="http://java.sun.com/jsf/facelets"
                 xmlns:p="http://primefaces.org/ui"
                 template="${template}"
                 xmlns:x="http://xpert.com/faces">
    <ui:param name="title" value="${sharp}{${resourceBundle}['${entity.nameLower}.list']}" />
    <ui:define name="body">
        <ui:include src="menu${entity.name}.xhtml" />
        <h:form id="formList${entity.name}">
            <x:modalMessages/>

            <x:dataTableActions fileName="${entity.nameLower}_export" target=":formList${entity.name}:dataTable${entity.name}"
                                     widgetVar="${entity.widgetVarDataTableName}"  />

            <p:dataTable paginator="true" rows="10" rowsPerPageTemplate="10,20,30" paginatorPosition="bottom" emptyMessage="${sharp}{xmsg['noRecordFound']}"
                         var="${entity.nameLower}" rowIndexVar="index" id="dataTable${entity.name}" widgetVar="${entity.widgetVarDataTableName}" styleClass="table-responsive"
                         currentPageReportTemplate="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.dataModel.currentPageReportTemplate}"
                         paginatorTemplate="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.dataModel.paginatorTemplate}"
                         value="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.dataModel}" lazy="true" >
                <p:column styleClass="uix-datatable-index">
                    <h:outputText value="${sharp}{index+1}"/>
                </p:column>
                <#list entity.fields as field>
                <#if field.collection == false && field.id == false>
                <p:column headerText="${sharp}{${resourceBundle}['${entity.nameLower}.${field.label}']}" sortBy="${sharp}{${entity.nameLower}.${field.name}}"
                    <#if field.string == true || field.integer == true || field.enumeration == true || field.yesNo == true || field.date == true>filterBy="${sharp}{${entity.nameLower}.${field.name}}"</#if> <#if field.yesNo == true>filterOptions="${sharp}{booleanSelectItensEmptyOption}"</#if> <#if field.enumeration == true>filterOptions="${sharp}{findAllBean.getSelect(class${configuration.managedBeanSuffix}.${field.typeNameLower})}"</#if> <#if field.date == true || field.time == true || field.yesNo == true>style="text-align: center;"</#if><#if field.decimal == true>style="text-align: right;"</#if>>
                    <f:facet name="header">
                        <h:outputText value="${sharp}{${resourceBundle}['${entity.nameLower}.${field.name}']}" />
                       <#if field.date == true>
                        <x:dateFilter/>
                        </#if>
                    </f:facet>
                    <#if field.lazy == true>
                    <h:outputText value="${sharp}{${entity.nameLower}.${field.name}}">
                        <x:initializer/>
                    </h:outputText>
                    </#if>
                    <#if field.decimal == true>
                    <h:outputText value="${sharp}{${entity.nameLower}.${field.name}}">
                        <f:convertNumber minFractionDigits="2" maxFractionDigits="2" />
                    </h:outputText>
                    </#if>
                    <#if field.date == true>
                    <h:outputText value="${sharp}{${entity.nameLower}.${field.name}}">
                        <f:convertDateTime />
                    </h:outputText>
                    </#if>
                    <#if field.time == true>
                    <h:outputText value="${sharp}{${entity.nameLower}.${field.name}}">
                        <f:convertDateTime pattern="${configuration.timePattern}"/>
                    </h:outputText>
                    </#if>
                    <#if field.yesNo == true>
                    <h:outputText value="${sharp}{${entity.nameLower}.${field.name}}" converter ="yesNoConverter" />
                    </#if>
                    <#if field.lazy == false && field.decimal == false && field.date == false && field.time == false && field.yesNo == false>
                    <h:outputText value="${sharp}{${entity.nameLower}.${field.name}}"/>
                    </#if>
                </p:column>
                </#if>
                </#list>
                <p:column styleClass="uix-datatable-actions" exportable="false" headerText="${sharp}{xmsg['actions']}">
                    <f:facet name="header">
                        <h:outputText value="${sharp}{xmsg['actions']}"/>
                    </f:facet>
                    <p:commandButton oncomplete="${entity.widgetVarDetail}.show();"  icon="ui-icon-zoomin" 
                                     process="@form" update=":formDetail${entity.name}" title="${sharp}{xmsg['detail']}" >
                        <f:setPropertyActionListener value="${sharp}{${entity.nameLower}}" target="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.entity}" />
                    </p:commandButton>
                    <#if entity.embeddedId == false && configuration.hideIdInRequest == false >
                    <#if configuration.generatesSecurityArea == true >
                    <x:securityArea rolesAllowed="${entity.nameLower}.create">
                        <p:button icon="ui-icon-pencil" outcome="create${entity.name}" title="${sharp}{xmsg['edit']}">
                            <f:param name="id" value="${sharp}{${entity.nameLower}.${entity.idFieldName}}" />
                        </p:button>
                    </x:securityArea>
                    <#else>
                    <p:button icon="ui-icon-pencil" outcome="create${entity.name}" title="${sharp}{xmsg['edit']}">
                        <f:param name="id" value="${sharp}{${entity.nameLower}.${entity.idFieldName}}" />
                    </p:button>
                    </#if>
                    <#else>
                    <#if configuration.generatesSecurityArea == true >
                    <x:securityArea rolesAllowed="${entity.nameLower}.create">
                        <p:commandButton icon="ui-icon-pencil"  action="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.putEntityInRequest}"
                                         ajax="false" title="${sharp}{xmsg['edit']}" >
                            <f:setPropertyActionListener value="${sharp}{${entity.nameLower}}" target="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.entity}" />
                            <f:setPropertyActionListener value="create${entity.name}" target="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.outcome}" />
                        </p:commandButton>
                    </x:securityArea>
                    <#else>
                    <p:commandButton icon="ui-icon-pencil"  action="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.putEntityInRequest}"
                                     ajax="false" title="${sharp}{xmsg['edit']}" >
                        <f:setPropertyActionListener value="${sharp}{${entity.nameLower}}" target="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.entity}" />
                        <f:setPropertyActionListener value="create${entity.name}" target="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.outcome}" />
                    </p:commandButton>
                    </#if>
                    </#if>
                    <#if configuration.generatesSecurityArea == true >
                    <x:securityArea rolesAllowed="${entity.nameLower}.delete">
                        <p:commandButton icon="ui-icon-trash" title="${sharp}{xmsg['delete']}" process="@form" update="@form" 
                                         action="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.delete}" >
                            <f:setPropertyActionListener value="${sharp}{${entity.nameLower}.${entity.idFieldName}}" target="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.id}" />
                            <x:confirmation message="${sharp}{xmsg['confirmDelete']} - ${sharp}{${entity.nameLower}}" />
                        </p:commandButton>
                    </x:securityArea>
                    <#else>
                    <p:commandButton icon="ui-icon-trash" title="${sharp}{xmsg['delete']}" process="@form" update="@form" 
                                     action="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.delete}" >
                        <f:setPropertyActionListener value="${sharp}{${entity.nameLower}.${entity.idFieldName}}" target="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.id}" />
                        <x:confirmation message="${sharp}{xmsg['confirmDelete']} - ${sharp}{${entity.nameLower}}" />
                    </p:commandButton>
                    </#if>
                </p:column>
            </p:dataTable>
            <div class="uix-audit-delete">
            <#if configuration.generatesSecurityArea == true >
                <x:securityArea rolesAllowed="${entity.nameLower}.audit">
                    <x:auditDelete for="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.entityClass}"/>
                </x:securityArea>
            <#else>
                <x:auditDelete for="${sharp}{${entity.nameLower}${configuration.managedBeanSuffix}.entityClass}"/>
            </#if>
            </div>  
        </h:form>

        <p:dialog widgetVar="${entity.widgetVarDetailName}" header="${sharp}{${resourceBundle}['${entity.nameLower}.detail']}" ${entity.appendTo} 
                  modal="true" <#if configuration.bootstrapVersion?? >styleClass="uix-dialog-fluid"<#else>height="500" width="800"</#if> >
                  <ui:include src="detail${entity.name}.xhtml" />
        </p:dialog>
    </ui:define>
</ui:composition>

xpert-framework-master/src/main/resources/com/xpert/maker/templates/view-menu.ftl
<ui:composition  xmlns="http://www.w3.org/1999/xhtml"
                 xmlns:h="http://java.sun.com/jsf/html"
                 xmlns:f="http://java.sun.com/jsf/core"
                 xmlns:ui="http://java.sun.com/jsf/facelets"
                 xmlns:p="http://primefaces.org/ui"
                 xmlns:x="http://xpert.com/faces">
    <p:toolbar>
        <p:toolbarGroup align="left">
            <#if configuration.generatesSecurityArea == true >
            <x:securityArea rolesAllowed="${entity.nameLower}.list">
                <p:button icon="ui-icon-search" value="${sharp}{xmsg['list']}" outcome="list${entity.name}" />
            </x:securityArea>
            <x:securityArea rolesAllowed="${entity.nameLower}.create">
                <p:button icon="ui-icon-plus" value="${sharp}{xmsg['create']}" outcome="create${entity.name}" />
            </x:securityArea>
            <#else>
            <p:button icon="ui-icon-search" value="${sharp}{xmsg['list']}" outcome="list${entity.name}" />
            <p:button icon="ui-icon-plus" value="${sharp}{xmsg['create']}" outcome="create${entity.name}" />
            </#if>
        </p:toolbarGroup>
    </p:toolbar>
</ui:composition>